### ISSUE TITLE
Generating version.hpp error

### ISSUE THREAD

**Issue by lmEshoo** [fprime-community/fprime-docker#3]
when following and checking the installation in the [install.md](https://github.com/nasa/fprime/blob/devel/docs/INSTALL.md#checking-your-f-installation)

```bash
fprime-util build --jobs "$(nproc || printf '%s\n' 1)"
```

I notice a failure as follows:

```bash
Scanning dependencies of target version
[ 77%] Generating version.hpp, __PHONY__
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/opt/fprime-3.0.0/cmake/target/version/generate_version_header.py", line 68, in <module>
    main()
  File "/opt/fprime-3.0.0/cmake/target/version/generate_version_header.py", line 64, in main
    create_version_file(fid)
  File "/opt/fprime-3.0.0/cmake/target/version/generate_version_header.py", line 50, in create_version_file
    fid.write('static const char* VERSION = "%s";\n' % (get_version_str()))
  File "/opt/fprime-3.0.0/cmake/target/version/generate_version_header.py", line 31, in get_version_str
    output = subprocess.check_output(["git", "describe", "--tags", "--always"])
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--always']' returned non-zero exit status 128.
make[3]: *** [CMakeFiles/version.dir/build.make:62: version.hpp] Error 1
make[3]: *** Deleting file 'version.hpp'
make[2]: *** [CMakeFiles/Makefile2:2168: CMakeFiles/version.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2148: CMakeFiles/Ref.dir/rule] Error 2
make: *** [Makefile:164: Ref] Error 2
[ERROR] CMake erred with return code 2
```

**Comment by lmEshoo** [comment]
@lestarch this may be due to the way I am downloading fprime. I am downloading the release like [so](https://github.com/fprime-community/fprime-docker/blob/devel/Dockerfile.ubuntu#L42). And looking at [cmake/target/version/generate_version_header.py](https://github.com/nasa/fprime/blob/devel/cmake/target/version/generate_version_header.py#L31) seems like it assumes a git clone of the repo. Is there a flag to disable this?

**Comment by LeStarch** [comment]
Not at this time.  I'll fix this in the next F´ release.  My thoughts are:

1. For a tagged source release, a version file should exist and feed this script
2. A script override should be used to allow for projects not using git

**Comment by lmEshoo** [comment]
I will stand by until next release.
